# Vectorization

In [ ]:
import numpy as np

a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
import time

a=np.random.rand(1000000)
b=np.random.rand(1000000)

tic=time.time() #현재 시간
c=np.dot(a,b)
toc=time.time()

print(c)
print("Vectorized version:" +str(1000*(toc-tic))+"ms") #밀리초 단위로 표현

250202.96287023884
Vectorized version:2.147674560546875ms


In [ ]:
c=0
tic=time.time()
for i in range (1000000):
  c +=a[i]*b[i]
toc=time.time()

print(c)
print("for loop:" + str(1000*(toc-tic))+"ms")

249756.92230481037
for loop:473.3731746673584ms


# Broadcasting in Python

In [1]:
import numpy as np

A=np.array([[56.0, 0.0, 4.4, 68.0],
            [1.2, 104.0, 52.0, 8.0],
            [1.8, 135.0, 99.0, 0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [2]:
cal=A.sum(axis=0) #열을 더함
print(cal)

[ 59.  239.  155.4  76.9]


In [3]:
percentage = 100*A/cal.reshape(1,4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


# A note on python/numpy vectors

In [4]:
import numpy as np
a=np.random.randn(5)

In [5]:
print(a)

[-0.55405951  0.6852566  -1.00746228  0.14955755 -1.21813413]


In [6]:
print(a.shape) #rank 1인 배열, 행/열 벡터 둘다 x

(5,)


In [7]:
print(a.T)

[-0.55405951  0.6852566  -1.00746228  0.14955755 -1.21813413]


In [8]:
print(np.dot(a,a.T))

3.2977570172311785


크기가 (n,)인 랭크가 1인 배열 사용하지 x

In [9]:
a=np.random.randn(5,1)
print(a) #a는 5x1 벡터

[[ 0.27149543]
 [-0.14281956]
 [-1.83525918]
 [ 0.40874818]
 [ 0.54109981]]


In [10]:
print(a.T)

[[ 0.27149543 -0.14281956 -1.83525918  0.40874818  0.54109981]]


In [11]:
print(np.dot(a,a.T)) #외적

[[ 0.07370977 -0.03877486 -0.49826448  0.11097326  0.14690612]
 [-0.03877486  0.02039743  0.26211091 -0.05837723 -0.07727964]
 [-0.49826448  0.26211091  3.36817627 -0.75015885 -0.9930584 ]
 [ 0.11097326 -0.05837723 -0.75015885  0.16707507  0.22117356]
 [ 0.14690612 -0.07727964 -0.9930584   0.22117356  0.29278901]]
