## Step 1. Library Import & Data Load

In [1]:
import pandas as pd
import numpy as np

In [9]:
train_df = pd.read_csv('/kaggle/input/nlp-getting-started/train.csv')
test_df = pd.read_csv('/kaggle/input/nlp-getting-started/test.csv')

In [3]:
train_df.head()

id keyword location                                               text  \
0   1     NaN      NaN  Our Deeds are the Reason of this #earthquake M...   
1   4     NaN      NaN             Forest fire near La Ronge Sask. Canada   
2   5     NaN      NaN  All residents asked to 'shelter in place' are ...   
3   6     NaN      NaN  13,000 people receive #wildfires evacuation or...   
4   7     NaN      NaN  Just got sent this photo from Ruby #Alaska as ...   

   target  
0       1  
1       1  
2       1  
3       1  
4       1

In [4]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7613 entries, 0 to 7612
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   id        7613 non-null   int64 
 1   keyword   7552 non-null   object
 2   location  5080 non-null   object
 3   text      7613 non-null   object
 4   target    7613 non-null   int64 
dtypes: int64(2), object(3)
memory usage: 297.5+ KB


In [5]:
train_df.nunique()

id          7613
keyword      221
location    3341
text        7503
target         2
dtype: int64

## Step 2. Data Preprocessing

### 2-a. Drop Columns

In [10]:
train_df.drop(columns=['id','keyword','location'], axis=1, inplace=True)
test_df.drop(columns=['keyword','location'],axis=1, inplace=True)

In [11]:
print(train_df.shape, test_df.shape)

(7613, 2) (3263, 2)


### 2-b. Tokenizer

In [13]:
from sklearn.model_selection import train_test_split

In [15]:
X_train, X_valid, y_train, y_valid = train_test_split(train_df['text'], train_df['target'], test_size=0.2, random_state=111)

In [16]:
print(X_train.shape, y_train.shape, X_valid.shape, y_valid.shape)

(6090,) (6090,) (1523,) (1523,)


In [17]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [18]:
vocab_size = 1000
oov_token = "<OOV>"
tokenizer = Tokenizer(num_words = vocab_size, oov_token = oov_token)

In [19]:
tokenizer.fit_on_texts(X_train)

In [20]:
X_train = tokenizer.texts_to_sequences(X_train)
X_valid = tokenizer.texts_to_sequences(X_valid)

In [21]:
for i in range(10):
    print(len(X_train[i]))

19
20
18
26
16
22
19
18
14
8


In [22]:
for i in range(10):
    print(len(X_valid[i]))

19
26
26
23
12
11
20
15
11
10


### 2-c. Pad Sequences

In [23]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [24]:
max_length = 120
trunc_type = 'post'
pad_type = 'post'

In [25]:
X_train_padded = pad_sequences(X_train, maxlen = max_length, truncating = trunc_type, padding = pad_type)
X_valid_padded = pad_sequences(X_valid, maxlen = max_length, truncating = trunc_type, padding=pad_type)

In [26]:
X_train_padded[:2]

array([[132,   1,   9, 324,  12,  16, 679,  13,   4,   2,   3,   1, 616,
        160,   1,   4,   2,   3,   1,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0],
       [826,   1, 140,  26,   1,   7,   6,   1,  23, 156,   1,  71, 181,
         14,   1,   1,   4,   2,   3,   1,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,

In [27]:
X_valid_padded[:2]

array([[ 73,  15, 231, 507,  18, 751, 397, 922, 175,   5,   1,   4,   2,
          3,   1,   4,   2,   3,   1,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0],
       [ 19,   1,  51, 551,  54,   7, 840,   6,   1,   1,  10,  79,  50,
        422,  34,  20,   6,   1,  10,  50,   1,  13,   1,  33,   1,   1,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,

In [28]:
print(X_train_padded.shape, X_valid_padded.shape)

(6090, 120) (1523, 120)


### 2-d. Match Data type to numpy.ndarray

In [29]:
print(type(X_train_padded), type(X_valid_padded))
print(type(y_train), type(y_valid))

<class 'numpy.ndarray'> <class 'numpy.ndarray'>
<class 'pandas.core.series.Series'> <class 'pandas.core.series.Series'>


In [31]:
y_train = np.array(y_train)
y_valid = np.array(y_valid)

In [32]:
print(type(X_train_padded), type(X_valid_padded))
print(type(y_train), type(y_valid))

<class 'numpy.ndarray'> <class 'numpy.ndarray'>
<class 'numpy.ndarray'> <class 'numpy.ndarray'>


### Step 3. Modeling

In [34]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Bidirectional, Flatten

In [35]:
embedding_dim = 16

In [37]:
model = Sequential([
    Embedding(vocab_size, embedding_dim, input_length = max_length),
    Bidirectional(LSTM(64, return_sequences=True)),
    Bidirectional(LSTM(64, return_sequences=True)),
    Bidirectional(LSTM(64, dropout=0.5)),
    Dense(32, activation='relu'),
    Dense(16, activation = 'relu'),
    Dense(1, activation='sigmoid')
])

In [38]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 120, 16)           16000     
_________________________________________________________________
bidirectional_2 (Bidirection (None, 120, 128)          41472     
_________________________________________________________________
bidirectional_3 (Bidirection (None, 120, 128)          98816     
_________________________________________________________________
bidirectional_4 (Bidirection (None, 128)               98816     
_________________________________________________________________
dense (Dense)                (None, 32)                4128      
_________________________________________________________________
dense_1 (Dense)              (None, 16)                528       
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 1

### Step 4. Model Compile

In [42]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])

### Step 5. Callbacks

In [39]:
from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping

In [40]:
filepath = 'my_checkpoint.ckpt'
cp = ModelCheckpoint(
    filepath = filepath,
    save_weights_only = True,
    save_best_only = True,
    monitor = 'val_loss',
    verbose = 1
)

In [41]:
ep = EarlyStopping(
monitor = 'val_loss',
patience = 5,)

### Step 6. Model Fit

In [43]:
epochs = 30
model.fit(
    X_train_padded, y_train,
    validation_data = (X_valid_padded, y_valid),
    callbacks=[cp, ep],
    epochs = epochs
)

Epoch 1/30
191/191 [==============================] - 18s 44ms/step - loss: 0.6352 - acc: 0.6277 - val_loss: 0.4813 - val_acc: 0.7774

Epoch 00001: val_loss improved from inf to 0.48131, saving model to my_checkpoint.ckpt
Epoch 2/30
191/191 [==============================] - 7s 35ms/step - loss: 0.4407 - acc: 0.8092 - val_loss: 0.4454 - val_acc: 0.7938

Epoch 00002: val_loss improved from 0.48131 to 0.44536, saving model to my_checkpoint.ckpt
Epoch 3/30
191/191 [==============================] - 7s 34ms/step - loss: 0.3863 - acc: 0.8396 - val_loss: 0.4421 - val_acc: 0.8083

Epoch 00003: val_loss improved from 0.44536 to 0.44205, saving model to my_checkpoint.ckpt
Epoch 4/30
191/191 [==============================] - 7s 34ms/step - loss: 0.3693 - acc: 0.8496 - val_loss: 0.4493 - val_acc: 0.7965

Epoch 00004: val_loss did not improve from 0.44205
Epoch 5/30
191/191 [==============================] - 7s 34ms/step - loss: 0.3515 - acc: 0.8645 - val_loss: 0.4872 - val_acc: 0.7991

Epoch 000

### Step 7. Model Evaluate & Save

In [44]:
model.load_weights(filepath)

In [46]:
model.evaluate(X_valid_padded, y_valid)

48/48 [==============================] - 1s 14ms/step - loss: 0.4421 - acc: 0.8083


[0.4420548379421234, 0.8082731366157532]

In [47]:
X_valid[0]

[73, 15, 231, 507, 18, 751, 397, 922, 175, 5, 1, 4, 2, 3, 1, 4, 2, 3, 1]

In [48]:
model.save('./model/basic_nlp.h5')

### Step 8. Reload Model

In [49]:
import tensorflow as tf

In [50]:
mymodel = tf.keras.models.load_model('./model/basic_nlp.h5')

In [51]:
mymodel.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 120, 16)           16000     
_________________________________________________________________
bidirectional_2 (Bidirection (None, 120, 128)          41472     
_________________________________________________________________
bidirectional_3 (Bidirection (None, 120, 128)          98816     
_________________________________________________________________
bidirectional_4 (Bidirection (None, 128)               98816     
_________________________________________________________________
dense (Dense)                (None, 32)                4128      
_________________________________________________________________
dense_1 (Dense)              (None, 16)                528       
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 1

### Step 9. Predict Test Data

In [52]:
X_test = tokenizer.texts_to_sequences(test_df['text'])

In [53]:
X_test_padded = pad_sequences(X_test, maxlen = max_length, truncating = trunc_type, padding=pad_type)

In [55]:
y_test_raw = model.predict(X_test_padded)

In [56]:
y_test_raw

array([[0.8396157 ],
       [0.45612046],
       [0.8556907 ],
       ...,
       [0.9813648 ],
       [0.9616656 ],
       [0.22286075]], dtype=float32)

In [57]:
y_test = list(map(lambda x : 1 if x > 0.5 else 0, y_test_raw))

In [58]:
set(y_test)

{0, 1}

In [59]:
test_df['predict'] = y_test

In [60]:
test_df[test_df['predict']==1]

id                                               text  predict
0         0                 Just happened a terrible car crash        1
2         3  there is a forest fire at spot pond, geese are...        1
4        11      Typhoon Soudelor kills 28 in China and Taiwan        1
5        12                 We're shaking...It's an earthquake        1
17       51  #PreviouslyOnDoyinTv: Toke Makinwa‰Ûªs marriag...        1
...     ...                                                ...      ...
3257  10858  The death toll in a #IS-suicide car bombing on...        1
3258  10861  EARTHQUAKE SAFETY LOS ANGELES ‰ÛÒ SAFETY FASTE...        1
3259  10865  Storm in RI worse than last hurricane. My city...        1
3260  10868  Green Line derailment in Chicago http://t.co/U...        1
3261  10874  MEG issues Hazardous Weather Outlook (HWO) htt...        1

[1097 rows x 3 columns]

In [61]:
submission = test_df[['id', 'predict']]

In [62]:
submission

id  predict
0         0        1
1         2        0
2         3        1
3         9        0
4        11        1
...     ...      ...
3258  10861        1
3259  10865        1
3260  10868        1
3261  10874        1
3262  10875        0

[3263 rows x 2 columns]